export default {
    counter:0,
    errorMsg: null,
    provider: null,
    providerLocation: null,
    addProviderLocation: null,
    parentLocations: null,
    groupLocations: null,
    providerLocations: null,
    parentProviderLocations: null,
    headerProviderLocations: [],
    dropdownProviderLocations: [],
    providerLocationsList: null,
    providerLocationById: null,
    subLocationsList: null,
    dropdownSubLocationsList: null,
    subLocationsByParentId: null,
    providersListAll: null,
    headerProvidersListAll: null,
    providerLocationList: null,
    editSingleProvider: null,
    getProviderPrograms: null,
    updateSingleProvider: null,
    providerMeta:null,
    editProviderLocation:null,
    locationPrograms:null,
    dropdownLocationPrograms:null,
    providerPrograms:null,
    providerTags:null,
    providerModules:null,
    selectedTags:null,
    selectedModules:null,
    programProviders:[],
    programsDropdown:'',
    providersDropdown:'',
    locationsDropdown:'',
    groupsDropdown:'',
    selectedProgram:'',
    selectedProvider:'',
    selectedLocation:'',
    selectedGroup:'',
    isManualHeader:false,
    providerContact:null,
    addProviderContact:null,
    assignProgramToLocation:null,
    addProviderSubLocation:null,
    locationLevel:'parent',
    providerData:null,
    updateProviderLocation:null,
    defaultProviderData:[],
    addedProviders:[],
    staffProviders:"",
    isEditProvider:false,
    headerGroups:[],
}